### ISSUE TITLE
adding help text to field group

### ISSUE THREAD

**Issue by VickyS08** [rsmithlal/ClimateDataRescue#10]
Monday May 30 @6:47 pm.  Tried to add help text to field group.

![screen shot 2016-05-30 at 6 46 06 pm](https://cloud.githubusercontent.com/assets/18540289/15659342/0d571e50-2697-11e6-8f59-f1edcb92093b.png)
![screen shot 2016-05-30 at 6 46 20 pm](https://cloud.githubusercontent.com/assets/18540289/15659341/0ae6bd60-2697-11e6-829e-5116ca4d21fb.png)

**Comment by jinxingster** [comment]
I think there is a length limit for the input text, default 255 characters.

On Mon, May 30, 2016 at 6:48 PM, VickyS08 <notifications@github.com> wrote:

> Monday May 30 @6 <https://github.com/6>:47 pm. Tried to add help text to
> field group.
>
> [image: screen shot 2016-05-30 at 6 46 06 pm]
> <https://cloud.githubusercontent.com/assets/18540289/15659342/0d571e50-2697-11e6-8f59-f1edcb92093b.png>
> [image: screen shot 2016-05-30 at 6 46 20 pm]
> <https://cloud.githubusercontent.com/assets/18540289/15659341/0ae6bd60-2697-11e6-829e-5116ca4d21fb.png>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/rsmithlal/ClimateDataRescue/issues/10>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/ACMy5szEs_d8UDCdBArw4DqxMD9luteuks5qG2lOgaJpZM4IqEM2>
> .
>



-- 
Jin Xing
Ph.D Candidate
McGill University
Montreal, QC, Canada

**Comment by VickyS08** [comment]
I cut and pasted the text from the help field under "observed barometer", to make that one a little shorter.  I also edited the other help fields to add in the expected range.

I'll put this into onenote later when I get to my computer, but I was thinking this morning about some of the remaining technical challenges:

1) symbols in drop down menus for weather - so far we have 1/2 of one page out of two : how to design the remaining fields? All in tabs in one bar, or separate bars?

2) associating the transcription bar with the ledger type 

3) having a test page/evaluate accuracy of typing page.  As a possible tutorial and to help users get used to the handwriting, I thought we could also have an example page somehow, where they could look at the page and see the typed values

4) French version


Vicky

**Comment by rsmithlal** [comment]
I can easily add a preview of the transcription bar to the ledger page, but it actually would belong on the page type detail page. The field groups are linked to the page types, as ledgers can have many different page types.

Regarding the French versions of the help text, I already have one of the two components in place for localized text on the site, and putting in localized attributes for the data will be trivial, I've done a lot of work with that module in the past.
