### ISSUE TITLE
'Draw a box' - "Annotation could not be saved | Bad request ! Error"

### ISSUE THREAD

**Issue by daZebra** [rsmithlal/ClimateDataRescue#12]
**Issue**
After submitting a transcription for the barometer group, I went straight to 'new annotation' without having drawn a box around the transcribed area. Then when I submitted the line of observations I got the following error.

**Potential Solution**
Could we disable the 'new annotation' button until the user has drawn the box?

![screen shot 2016-08-29 at 8 58 41 am](https://cloud.githubusercontent.com/assets/14224342/18057185/ebaa9786-6ddc-11e6-8aaf-80b2e2538bde.png)

**Comment by rsmithlal** [comment]
This has been implemented
