### ISSUE TITLE
'Draw a box' - Unable to edit the box after clicking.

### ISSUE THREAD

**Issue by daZebra** [rsmithlal/ClimateDataRescue#16]
**Issue**
I often make mistakes when drawing the box. 
It would be great to have the ability to edit it.

**Comment by rsmithlal** [comment]
You mean the dimensions and position of the box right? If so, yes this is an important feature that will be added.

**Comment by daZebra** [comment]
Yes dimensions and position.

**Comment by rsmithlal** [comment]
This has been implemented.
