### ISSUE TITLE
Transcription bar - Can't see 'Observation time' because it gets cropped

### ISSUE THREAD

**Issue by daZebra** [rsmithlal/ClimateDataRescue#17]
**Issue**
The observation time does not display all at once because it is too big for the field. 
![screen shot 2016-08-31 at 1 44 32 pm](https://cloud.githubusercontent.com/assets/14224342/18139865/32ceb0a2-6f81-11e6-8075-7a1698b83cd3.png)
Hence, part of it gets cropped, making it impossible to see the entire value. This can lead to more errors (e.g. can't see that I put 'pm' instead of 'am').
Moreover, I find that re-writing the date for every transcription is a pain in the neck.

**Potential solution**
Turn the 'observation time' field in to a Select2. This would also make it more user friendly.

**Comment by rsmithlal** [comment]
Done
