### ISSUE TITLE
Type_A2 page appeared after clicking on 'New transcription'

### ISSUE THREAD

**Issue by daZebra** [rsmithlal/ClimateDataRescue#19]
I don't think we should be getting Type_A2 pages at the moment right?

![image](https://cloud.githubusercontent.com/assets/14224342/18140512/df392faa-6f83-11e6-8758-42b18c983c2b.png)
![image](https://cloud.githubusercontent.com/assets/14224342/18140516/e2aefd72-6f83-11e6-850b-745b79aa6234.png)

**Comment by rsmithlal** [comment]
I included type 2 pages before our last meeting. Now that we have the field options we can begin adding field groups to page type A2. You can begin adding fields and field groups for page type A2.

**Comment by rsmithlal** [comment]
Even if the options functionality is not 100% complete, this process can begin.
