### ISSUE TITLE
Can scroll up indefinitely

### ISSUE THREAD

**Issue by daZebra** [rsmithlal/ClimateDataRescue#23]
**Issue**
I can move the header placeholder up infinitely. At some point I no longer see the image. It can get confusing for a beginner user.

**Potential Solution**
Prevent scrolling up beyond a certain point.

![infinite-scroll-up](https://cloud.githubusercontent.com/assets/14224342/18141531/d96f042e-6f87-11e6-941d-6a7c60089010.gif)

**Comment by rsmithlal** [comment]
That gif is awesome, I like that as a way to illustrate an issue! Also this is a good improvement.

**Comment by rsmithlal** [comment]
This has been addressed.
