### ISSUE TITLE
Safari User?

### ISSUE THREAD

**Issue by daZebra** [rsmithlal/ClimateDataRescue#24]
**Issue**
The 'Safari User' text takes up a lot of space.

**Potential Solution**
We only put 'Safari User' as a hyperlink to the FAQ question where we explain this.

![image](https://cloud.githubusercontent.com/assets/14224342/18141586/13121306-6f88-11e6-9c79-8b29400b2f82.png)

**Comment by rsmithlal** [comment]
This is a good improvement

**Comment by rsmithlal** [comment]
This has been addressed by replacing the normal time field with a time picker.
