### ISSUE TITLE
Transcription bar - Reinitialize Select2 fields

### ISSUE THREAD

**Issue by daZebra** [rsmithlal/ClimateDataRescue#25]
**Issue**
The Select2 fields retain their previous values when the transcription bar is reopened. This is somewhat confusing to the user - makes it seem like it didn't save properly.

**Potential Solution**
Reinitialize all fields except for date and time.

**Comment by rsmithlal** [comment]
I'll keep the date, but the time will likely be different, so better to have it cleared as well.
