### ISSUE TITLE
[BROKEN!] 'New Annotation' not working

### ISSUE THREAD

**Issue by daZebra** [rsmithlal/ClimateDataRescue#26]
**Issue**
The transcription bar does not appear when I click on 'new annotation' on the transcription page.
Also, the page doesn't display the rectangles that I had previously drawn. It looks as though I have never been on that page despite the fact that I have entered 17 annotations (according to the annotation count).

**Comment by rsmithlal** [comment]
Sounds like an error in the JS. Can I get the URL of the page you were transcribing? I need more details to be able to replicate this. Please try to include a url for the page in question for all issue reports. If it's an issue with the field options or transcriptions, please open your javascript console and report and errors or messages present there. Thanks!

**Comment by rsmithlal** [comment]
Sounds like an error in the JS. Can I get the URL of the page you were transcribing? I need more details to be able to replicate this. Please try to include a url for the page in question for all issue reports. If it's an issue with the field options or transcriptions, please open your javascript console and report and errors or messages present there. Thanks!

**Comment by daZebra** [comment]
Yes, my bad. I thought the issue was generalized to all pages.
Url: http://test.citsci.geog.mcgill.ca/transcriptions/27/edit
JS-Console: 
![screen shot 2016-09-01 at 10 14 18 am](https://cloud.githubusercontent.com/assets/14224342/18170637/f9793fa0-702c-11e6-9578-2bd77afbcbd2.png)

**Comment by rsmithlal** [comment]
fixed in 609454ae5917de407454129cee6ef8b874e7698d, it's working now
