### ISSUE TITLE
[BROKEN!] 'New Transcription' not working

### ISSUE THREAD

**Issue by daZebra** [rsmithlal/ClimateDataRescue#27]
**Issue**
When I click on 'New Transcription' from the 'Actions' navigation menu, I end up here instead of on the new transcription page.
![screen shot 2016-09-01 at 9 31 52 am](https://cloud.githubusercontent.com/assets/14224342/18169512/69ec5a60-7028-11e6-9b6b-a9db7e20b237.png)

**Comment by rsmithlal** [comment]
Thanks for logging this! Just so you know, that is the correct page but I need to update the function used to choose the image. There is a page selected, but it doesn't have any field groups linked to its page type so it's not displayed.

**Comment by rsmithlal** [comment]
Thanks for logging this! Just so you know, that is the correct page but I need to update the function used to choose the image. There is a page selected, but it doesn't have any field groups linked to its page type so it's not displayed.

**Comment by rsmithlal** [comment]
Thanks for logging this! Just so you know, that is the correct page but I need to update the function used to choose the image. There is a page selected, but it doesn't have any field groups linked to its page type so it's not displayed.
