### ISSUE TITLE
[very minor issue] Field group colour automatically reverts to purple when editing

### ISSUE THREAD

**Issue by daZebra** [rsmithlal/ClimateDataRescue#28]
**Issue**
Whenever I edit a field group, it's display colour reverts back to purple by default. Hence, if we make changes to a field group but forget to change it's colour back to what it was, the transcription bar will end up all purple.

Example:
Try editing 'Wet Bulb'. Click save without changing anything. It's colour on the transcription bar will no longer be green; it'll be purple.

**Comment by rsmithlal** [comment]
Fixed
