### ISSUE TITLE
Field Options: move 'Illegible' and 'Empty' at the bottom of the list

### ISSUE THREAD

**Issue by daZebra** [rsmithlal/ClimateDataRescue#29]
It would be more intuitive to have 'Illegible' and 'Empty' at the bottom of the options list rather than at the very top.
![screen shot 2016-09-05 at 9 45 28 am](https://cloud.githubusercontent.com/assets/14224342/18249700/e17b10e4-734d-11e6-920e-25d9361f7a55.png)

**Comment by rsmithlal** [comment]
Done
