### ISSUE TITLE
[Very minor issue]  'Editing Field' page: roll-over text never dissapears

### ISSUE THREAD

**Issue by daZebra** [rsmithlal/ClimateDataRescue#31]
**Issue**
The rollover text that when hovering on the green '+' signs or the red 'x' signs continuous to display after having clicked it. It can get in the way when the rollover text displays on top of the '+' sign, making it impossible to click it.
![screen shot 2016-09-05 at 4 46 48 pm](https://cloud.githubusercontent.com/assets/14224342/18256872/5877b32e-7389-11e6-84b6-b7a57b44cfdd.png)

_url:_http://test.citsci.geog.mcgill.ca/fields/17/edit
_time:_ ~4:45PM

**Comment by rsmithlal** [comment]
This has been addressed.
