### ISSUE TITLE
[Layout Issue] Main content is not centered

### ISSUE THREAD

**Issue by daZebra** [rsmithlal/ClimateDataRescue#33]
**Issue**
The HTML injected in the <div ID="page_content"> is not centered on the page. Moreover, the 'Actions' sidebar gets moved down to the bottom of the page when padding is added inside the "page_content" area.
![screen shot 2016-09-12 at 4 30 46 pm](https://cloud.githubusercontent.com/assets/14224342/18451870/b1c94776-7906-11e6-9962-a633d1382e38.png)

**Comment by rsmithlal** [comment]
Fixed
