### ISSUE TITLE
[Minor issue] Transcription bar - Stacked field groups

### ISSUE THREAD

**Issue by daZebra** [rsmithlal/ClimateDataRescue#34]
**Issue**
When I click on the 'Wet Bulb' field, the transcription bar becomes narrower because there are fewer fields in that group. As a result, the field groups get squished together and the 'Rain' and 'Snow' field groups are moved below the first line. 
![screen shot 2016-09-13 at 11 58 53 am](https://cloud.githubusercontent.com/assets/14224342/18481365/f26725c0-79a9-11e6-92fd-1a5e4f19ea41.png)

**Comment by rsmithlal** [comment]
Addressed. When the fields wrap, the display is better. They still wrap, though.
