### ISSUE TITLE
Minor CSS Adjustments

### ISSUE THREAD

**Issue by daZebra** [rsmithlal/ClimateDataRescue#37]
**Home Page**
_Before_
![screen shot 2016-09-15 at 11 05 05 am](https://cloud.githubusercontent.com/assets/14224342/18555264/3feff3ee-7b35-11e6-87d0-e6a67a0239a4.png)
_After_
![screen shot 2016-09-15 at 11 04 57 am](https://cloud.githubusercontent.com/assets/14224342/18555265/41f52808-7b35-11e6-85eb-11c8dda67729.png)
_Modifications_
`.body-bg-img {
      opacity: 1;
   }
   p.homepage-intro {
      padding: 0 20px;
      text-align: center;
   }`
Note: change the opacity to 100% on all pages.
<hr>
**Content Pages**
_Before_
![screen shot 2016-09-15 at 11 04 39 am](https://cloud.githubusercontent.com/assets/14224342/18555416/cb268338-7b35-11e6-82cc-ffa5ef287947.png)
_After_
![screen shot 2016-09-15 at 11 04 29 am](https://cloud.githubusercontent.com/assets/14224342/18555421/d07a7fec-7b35-11e6-9ce4-c4f274007260.png)
_Modifications_
`
   h1 {
      color:#fff;
   }
   .main-app .main-content-container.default {`
       ~~background-color: rgba(253,253,253,0.8);~~
`   }
   .main-wrapper {
      background-color: rgba(0,0,0,0.3);
   }
`
<hr>
**Admin Pages**
_Before_
![screen shot 2016-09-15 at 11 07 28 am](https://cloud.githubusercontent.com/assets/14224342/18555829/4639f3f6-7b37-11e6-8260-d3e1579158c5.png)
_After_
![screen shot 2016-09-15 at 11 07 16 am](https://cloud.githubusercontent.com/assets/14224342/18555825/42cc1aa0-7b37-11e6-9071-f36cfb473bbd.png)
_Modifications_
`
.main-app .main-content-container.default {
    background-color: rgba(253,253,253,1);
    min-height: 300px;
}
`

**Comment by rsmithlal** [comment]
Changes have been made
