### ISSUE TITLE
Add "Transcribe" button to Nav-Bar

### ISSUE THREAD

**Issue by daZebra** [rsmithlal/ClimateDataRescue#38]
**Issue**
Now that the side-bar is gone, it will be less straightforward for new users to start a new transcription.
Thus, it may be desirable to add a "Transcribe" button to the nav-bar, with two sub-menu items: "New transcription" and "My transcriptions".

**Comment by rsmithlal** [comment]
"My Transcriptions" has been moved to "My Profile", so I can add an alias link to it in that menu you're suggesting

**Comment by daZebra** [comment]
Another option would be to rename "Weather Logs" to "Transcribe" and to put "FAQs and "Tutorial" as drop down items under the "Help" nav-bar button.

**Comment by rsmithlal** [comment]
Yeah that's not a bad idea. I could set up a parent-child relationship for content pages for dropdown nesting

**Comment by daZebra** [comment]
I guess those are all things that can be tested in the study groups. New users will probably have interesting input regarding the navigation on the website.

**Comment by rsmithlal** [comment]
This has been added
