### ISSUE TITLE
Transcription Process - Can draw infinite number of boxes

### ISSUE THREAD

**Issue by daZebra** [rsmithlal/ClimateDataRescue#47]
**Issue: I can draw an infinite number of boxes**
After transcribing the barometer group, I drew the first box. All good.
Then I reopened the transcription bar for the next annotation. When I tried to move the background image of the ledger sideways, it drew another box...again and again.

![ezgif com-optimize](https://cloud.githubusercontent.com/assets/14224342/19484476/c1479190-9525-11e6-8516-22cb0f21987f.gif)

**Comment by rsmithlal** [comment]
Issue resolved
