### ISSUE TITLE
[DRAW-002] ‘Transcribe’ button should appear as ‘Continue Transcribing’ on ‘My Transcriptions’ page

### ISSUE THREAD

**Issue by Tiffanyhi** [rsmithlal/ClimateDataRescue#52]
Steps to reproduce:
1. Complete the transcription of a row and save.
2. Navigate to another section of the website. 
3. Navigate to ‘My Transcriptions’ by selecting the ‘Transcribe’ tab, then ‘My Transcriptions’ on the drop-down.
4. Observe ‘Transcribe’ button.

Recommended result:
‘Transcribe’ button should appear as ‘Continue Transcribing’ on ‘My Transcriptions’ page.

Actual result: 
The button to continue previous transcribes appears as ‘Transcribe’.

Notes:
Tested on:
Google Chrome Version 55.0.2883.87 m, Internet Explorer 11, Firefox version 37.0.1.
Windows 7 Professional x32, Intel Cote i5, ATI Radeon HD 4550.
Repro rate: 5/5.

Screenshot attached: DRAW-002.png

Tiffany Hirsch

![draw-002](https://cloud.githubusercontent.com/assets/25228995/22117234/45b7ddf4-de41-11e6-86c4-bba1cf7079f6.png)

**Comment by rsmithlal** [comment]
Now reads "Edit transcription"
