### ISSUE TITLE
[DRAW-003] Edit options are not functional when transcription box is too thin

### ISSUE THREAD

**Issue by Tiffanyhi** [rsmithlal/ClimateDataRescue#53]
Steps to reproduce:
1. Start a new transcription.
2. Enter row data, sizing the transcription box thinner than the length of the edit option buttons. 
3. After the box is created, cover over it to prompt edit option buttons.
4. Click the edit option buttons. 

Recommended result:
Edit option buttons should be function even if the length of the box is too thin to display the entire button.
Or
Transcription box sizing is required to be at least the length of the edit option buttons.

Actual result:
Edit options are not functional when transcription box is too thin.

Notes:
Tested on:
Google Chrome Version 55.0.2883.87 m, Internet Explorer 11, Firefox version 37.0.1.
Windows 7 Professional x32, Intel Cote i5, ATI Radeon HD 4550.
Repro rate: 5/5.

Screenshot attached: DRAW-003.png

Tiffany Hirsch

![draw-003](https://cloud.githubusercontent.com/assets/25228995/22117381/c027623a-de41-11e6-959a-ecfc23de79fe.png)

**Comment by rsmithlal** [comment]
Resolved by setting a min width and height for annotation boxes
