### ISSUE TITLE
[DRAW-004] Buttons on the ‘Start a New Transcription’ page do not properly align

### ISSUE THREAD

**Issue by Tiffanyhi** [rsmithlal/ClimateDataRescue#54]
Steps to reproduce:
1. Navigate to the ‘Start a New Transcription’ page http://test.citsci.geog.mcgill.ca/transcriptions/new.
2. Observe buttons not aligning properly.

Recommended result:
Align the two buttons horizontally rather than stacking them vertically.
However, if wishing to keep them stacked vertically, align both buttons to the left side.

Actual result:
Buttons on the ‘Start a New Transcription’ page do not properly align.

Notes:
Tested on:
Google Chrome Version 55.0.2883.87 m, Internet Explorer 11, Firefox version 37.0.1.
Windows 7 Professional x32, Intel Cote i5, ATI Radeon HD 4550.
Repro rate: 5/5.

Tiffany Hirsch

Screenshot attached: DRAW-004.png
![draw-004](https://cloud.githubusercontent.com/assets/25228995/22119315/219a24ce-de49-11e6-81bc-5334f91f22e4.png)

**Comment by rsmithlal** [comment]
Resolved
