### ISSUE TITLE
[DRAW-005] Data entered in transcription pop-up does not save after clicking and dragging box

### ISSUE THREAD

**Issue by Tiffanyhi** [rsmithlal/ClimateDataRescue#55]
Steps to reproduce:
1. Navigate to a new transcription.
2. Select ‘transcribe’ button to begin transcription process.
3. When data entry pop-up prompts, enter in values and select ‘save’.
4. Click and drag box around the data just transcribed.
5. Data entry pop-up prompts a second time. None of the previous data entered is saved. Instead, these sections appear as empty. 

Recommended result:
Data should save after submitting the first time and should be appear with its respective box. 

Actual result:
Data entered in transcription pop-up does not save after clicking and dragging box. The user is required to submit the data during the second time in order for it to save.

Notes:
Tested on:
Google Chrome Version 55.0.2883.87 m, Internet Explorer 11, Firefox version 37.0.1.
Windows 7 Professional x32, Intel Cote i5, ATI Radeon HD 4550.
Repro rate: 5/5.

Screenshot attached: DRAW-005.png

Tiffany Hirsch

![draw-005](https://cloud.githubusercontent.com/assets/25228995/22123392/6eed6050-de59-11e6-8cb5-e661e677bab2.png)

**Comment by rsmithlal** [comment]
Resolved
