### ISSUE TITLE
[DRAW-008] Scrollbar overlaps top right of navigation menu when using Internet Explorer

### ISSUE THREAD

**Issue by Tiffanyhi** [rsmithlal/ClimateDataRescue#58]
Steps to reproduce:
1. Launch DRAW website using Internet Explorer.
2. Observe the top right of the navigation menu overlapping with the scrollbar.

Actual result:
Scrollbar overlaps the top right of the navigation menu when using Internet Explorer.

Expected results:
The navigation menu is provided with enough room to not overlap the scrollbar.

Notes:
Issue occurs on: Internet Explorer 11.
Issue does not occur on: Google Chrome Version 55.0.2883.87 m, Firefox version 37.0.1.
Tested on: Windows 7 Professional x32, Intel Cote i5, ATI Radeon HD 4550.
Repro rate: 5/5.
Screenshots attached: DRAW-008.png

Tiffany Hirsch

![draw-008](https://cloud.githubusercontent.com/assets/25228995/22127188/eaf6533c-de68-11e6-85ea-ef157443c02e.png)

**Comment by rsmithlal** [comment]
IE is low priority
