### ISSUE TITLE
[DRAW-010] On ‘Help Guide’ page, there is a missing link where text says ‘click here’ 

### ISSUE THREAD

**Issue by Tiffanyhi** [rsmithlal/ClimateDataRescue#60]
Steps to reproduce:
1. Launch DRAW website.
2. Navigate to the ‘Help Guide’ section http://test.citsci.geog.mcgill.ca/help-guide.
3. Observe missing link where text says ‘click here’.

Actual result:
On ‘Help Guide’ page, there is a missing link where text says ‘click here’.

Expected result:
Text which says ‘click here’ is clickable. 

Notes:
Issue occurs on:
Google Chrome Version 55.0.2883.87 m, Internet Explorer 11, Firefox version 37.0.1.
Windows 7 Professional x32, Intel Cote i5, ATI Radeon HD 4550.
Repro rate: 5/5.

Screenshots attached: DRAW-010.png

Tiffany Hirsch

![draw-010](https://cloud.githubusercontent.com/assets/25228995/22335304/32387d9a-e3ac-11e6-85da-88a796c7bf2e.png)

**Comment by rsmithlal** [comment]
App content problem, not mine
