### ISSUE TITLE
[DRAW-011] Replace background photo of Roddick Gates with McGill Observatory

### ISSUE THREAD

**Issue by Tiffanyhi** [rsmithlal/ClimateDataRescue#61]
Steps to reproduce:
1. Launch DRAW website http://test.citsci.geog.mcgill.ca/.
2. Observe background photo.

Actual result:
Website background is a photo of Roddick Gates.

Expected result:
Replace background photo of Roddick Gates with McGill Observatory.

Notes:
Issue occurs on:
Google Chrome Version 55.0.2883.87 m, Internet Explorer 11, Firefox version 37.0.1.
Windows 7 Professional x32, Intel Cote i5, ATI Radeon HD 4550.
Repro rate: 5/5.

Screenshots attached: DRAW-011.png

Tiffany Hirsch

![draw-011](https://cloud.githubusercontent.com/assets/25228995/22335911/71ff044c-e3ae-11e6-8dc7-2fcd5ed60582.png)

**Comment by rsmithlal** [comment]
Won't be done for now
