### ISSUE TITLE
[DRAW-015] No character limit exists for the Website Feedback fields

### ISSUE THREAD

**Issue by Tiffanyhi** [rsmithlal/ClimateDataRescue#65]
Steps to reproduce:
1. Launch DRAW website.
2. Navigate to the ‘User Feedback’ page http://test.citsci.geog.mcgill.ca/feedback.
3. Enter in a vast amount of characters in any of the fields.
4. Select ‘submit’.

Actual result:
No character limit exists for the Website Feedback fields. As such, the user can input as many characters as they would like. This includes the name and email fields. 

Expected result:
A character limit should exist for the Website Feedback fields, especially the name and email sections.

Notes:
Issue occurs on:
Google Chrome Version 55.0.2883.87 m, Internet Explorer 11, Firefox version 37.0.1.
Windows 7 Professional x32, Intel Cote i5, ATI Radeon HD 4550.
Repro rate: 5/5.

Screenshots attached: DRAW-015.png

Tiffany Hirsch

![draw-015](https://cloud.githubusercontent.com/assets/25228995/22343412/f6d643a8-e3c5-11e6-84d1-163951f44c20.png)

**Comment by rsmithlal** [comment]
This is all google forms, not related to the website and nothing I can do about this.
