### ISSUE TITLE
[DRAW-016] In Website Feedback, user can input an email address missing @ and a domain

### ISSUE THREAD

**Issue by Tiffanyhi** [rsmithlal/ClimateDataRescue#66]
Steps to reproduce:
1. Launch DRAW website.
2. Navigate to the ‘User Feedback’ page http://test.citsci.geog.mcgill.ca/feedback.
3. In email address field, enter text but do not include @ and a domain (ex: 12345).
4. Select ‘submit’.

Actual result:
In the email address field, the user is permitted to enter an address excluding @ and a domain. There is no error message present stating that the user must include @ and a domain within their email address.

Expected result: 
In the email address field, the user should be required to include @ and a domain. If not included, an error message should prompt, confirming that the provided email address does not exist.

Notes:
Issue occurs on:
Google Chrome Version 55.0.2883.87 m, Internet Explorer 11, Firefox version 37.0.1.
Windows 7 Professional x32, Intel Cote i5, ATI Radeon HD 4550.
Repro rate: 5/5.

Screenshots attached: DRAW-016.png

Tiffany Hirsch

![draw-016](https://cloud.githubusercontent.com/assets/25228995/22345970/4a39a274-e3d0-11e6-8f77-99e44b537686.png)

**Comment by rsmithlal** [comment]
This is all google forms, not related to the website and nothing I can do about this.
