### ISSUE TITLE
[DRAW-018] Reverse Clouds and Wind on transcription bar

### ISSUE THREAD

**Issue by Tiffanyhi** [rsmithlal/ClimateDataRescue#68]
Steps to reproduce:
1. Launch DRAW website.
2. Start a new transcription. 
3. Select the ‘Transcribe’ button to launch the transcribe bar.

Actual result:
The Clouds and Wind tabs on the transcribe bar appear reversed to how they appear on the register form.

Expected result:
The Clouds and Wind tabs on the transcribe bar appear in the same order as on the register form.

Notes:
Issue occurs on:
Google Chrome Version 55.0.2883.87 m, Internet Explorer 11, Firefox version 37.0.1.
Windows 7 Professional x32, Intel Cote i5, ATI Radeon HD 4550.
Repro rate: 5/5.

Screenshots attached: DRAW-018.png

Tiffany Hirsch

![draw-018](https://cloud.githubusercontent.com/assets/25228995/22788435/d0a2b462-eead-11e6-91f4-a9aabf8d61d5.png)

**Comment by rsmithlal** [comment]
You can do this, just go to that page's page type in the admin section and drag the field group in the position you want. Anything related to app contents should be directed to Vicky or Lori. I only deal with the code problems.

**Comment by rsmithlal** [comment]
Data config issue
