### ISSUE TITLE
[DRAW-020] Text does not align properly within some of the transcribe drop-downs

### ISSUE THREAD

**Issue by Tiffanyhi** [rsmithlal/ClimateDataRescue#69]
Steps to reproduce:
1. Launch DRAW website using Chrome or Firefox.
2. Start a new transcription. 
3. Select multiple tabs, such as ‘Wind’ and ‘Clouds’.
4. Select drop-downs from the tabs, such as ‘Wind Direction’ in the ‘Wind’ tab and ‘Lower Clouds’ in the ‘Clouds’ tab. 

Actual result:
Text does not align properly within some of the transcribe drop-downs. As such, the text appears cut off, only being readable fully when scrolled using the vertical scrollbar (which appears at the bottom of these drop-downs). 
A possible solution for this issue could be to increase the width of these drop-down boxes.

Expected result:
All text is readable within the drop-downs.

Notes:
Issue occurs on:
Google Chrome Version 55.0.2883.87 m, Firefox version 37.0.1.
Issue does not occur on: 
Internet Explorer 11 (Due to issue: DRAW-017).
Tested on: Windows 7 Professional x32, Intel Cote i5, ATI Radeon HD 4550.
Repro rate: 5/5.

Screenshots attached: DRAW-020.png

Tiffany Hirsch

![draw-020](https://cloud.githubusercontent.com/assets/25228995/23038045/95835b58-f456-11e6-9348-8bc08a9eea8a.png)

**Comment by rsmithlal** [comment]
Resolved. Select2 is now wider.
