### ISSUE TITLE
[DRAW-021] Some navigation headers appear highlighted

### ISSUE THREAD

**Issue by Tiffanyhi** [rsmithlal/ClimateDataRescue#71]
Steps to reproduce:
1. Launch DRAW homepage on any browser http://test.citsci.geog.mcgill.ca/en.
2. Observe navigation headers.

Actual result:
Some navigation headers, such as ‘Log In’, ‘Signup’, ‘Start Transcribing’, and ‘What is Draw’, appear highlighted. This gives the user the impression that they are selected.

Expected result:
Headers only appear highlighted when selected. 

Notes:
Issue occurs on:
Google Chrome Version 55.0.2883.87 m, Firefox version 37.0.1., Internet Explorer 11.
Tested on: Windows 7 Professional x32, Intel Cote i5, ATI Radeon HD 4550.
Repro rate: 5/5.

Screenshots attached: DRAW-021.png

Tiffany Hirsch

![draw-021](https://cloud.githubusercontent.com/assets/25228995/23265470/a9c84c7a-f9b2-11e6-8454-23367bc6b63f.png)

**Comment by rsmithlal** [comment]
Hi Tiffany,
I explained this in the meeting that we had on Tuesday evening. This new style was added to distinguish texts that do not have translations from those that do. Any text that appears "highlighted" is ready to be translated but does not have a translation in the database for the current language. As soon as a translation is added for the specified language and key, this will disappear.
