### ISSUE TITLE
[DRAW-022] Translation missing message appears after selecting ‘Take a break’

### ISSUE THREAD

**Issue by Tiffanyhi** [rsmithlal/ClimateDataRescue#72]
Steps to reproduce:
1. Launch DRAW website.
2. Continue a previous transcription or start a new one. 
3. Once on the transcribe page, select the 'Stop Transcribing' button, then select the 'Take a Break'.
4. After redirected to 'My Transcriptions' page, observe error message at the top of screen.

Actual result:
An error message appears after selecting 'Take a break'. This message reads: 'translation missing: en.transcription-saved-msg'

Expected result:
No error messages should appear after selecting ‘Take a break’.

Notes:
Issue occurs on:
Google Chrome Version 55.0.2883.87 m, Firefox version 37.0.1., Internet Explorer 11.
Tested on: Windows 7 Professional x32, Intel Cote i5, ATI Radeon HD 4550.
Repro rate: 5/5.

Screenshots attached: DRAW-022.png

Tiffany Hirsch

![draw-022](https://cloud.githubusercontent.com/assets/25228995/24763166/955ab944-1abe-11e7-83f8-aecce272ab9d.png)

**Comment by rsmithlal** [comment]
Not a bug, just missing translation value. This is the expected behaviour.
