### ISSUE TITLE
Can't have spaces between words

### ISSUE THREAD

**Issue by Sneaky-Owl** [rsmithlal/ClimateDataRescue#74]
Notes of version:
1) Google Chrome Version 58.0.3029.81 (64-bit) on a MacBook Pro (OS Sierra version 10.12.4)
2) Firefox 3.9 on Windows 7 HP desktop
3) Google Chrome 57.0.2987.133 on Windows 7 HP desktop

The Remarks field (once doing the transcription) is made up of full sentences. The system does not allow you to put spaces between words so it ends up looking like a long string.

**Comment by rsmithlal** [comment]
This has been resolved. Please test on the test site and confirm, then close.

**Comment by Sneaky-Owl** [comment]
Perfect! Thank you!
