### ISSUE TITLE
Cannot click on third date

### ISSUE THREAD

**Issue by Sneaky-Owl** [rsmithlal/ClimateDataRescue#75]
Notes of version:
1) Google Chrome Version 58.0.3029.81 (64-bit) on a MacBook Pro (OS Sierra version 10.12.4)
2) Firefox 3.9 on Windows 7 HP desktop
3) Google Chrome 57.0.2987.133 on Windows 7 HP desktop

When changing the date, it does not allow you to click on the third date (the 11th in the example below) and it does not allow you to type it on manually. 

<img width="1280" alt="screen shot 2017-04-26 at 2 53 36 pm" src="https://cloud.githubusercontent.com/assets/28064147/25451448/358316ec-2a90-11e7-9c1c-e12c61838e5a.png">
<img width="1280" alt="screen shot 2017-04-26 at 2 53 40 pm" src="https://cloud.githubusercontent.com/assets/28064147/25451457/3b36fd56-2a90-11e7-81b3-7182787aa7d2.png">

**Comment by rsmithlal** [comment]
Resolved
